### GENERAL SETTINGS ###

# Site settings
title: Miguel Hernández
description: "Dejando rastro de mi viaje hacia el conocimiento, compartiendo algunas historias y los proyectos más interesantes con los que me he tenido que topar y superar."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "https://madh93.github.io"

# Build settings
markdown: kramdown
permalink: /:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url: https://github.com/Madh93
  - title: linkedin
    url: https://es.linkedin.com/in/migueldhdez
  - title: facebook
    url: https://www.facebook.com/liSv010
  - title: twitter
    url: https://twitter.com/madh93

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Mi habitación,
    - Santa Cruz de Tenerife,
    - España.

email: migueldhdez@gmail.com


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Personal information. Shown on About page.
me:
  - name: Miguel Hernández
    position: Ingeniero informático
    text: Con ganas de compartir con más personas lo poco que voy aprendiendo en mi día a día en la carrera.
    img: me.jpg
    social:
      - title: envelope #use for email address
        url: mailto:migueldhdez@gmail.com
      - title: github
        url: https://github.com/Madh93
      - title: linkedin
        url: https://es.linkedin.com/in/migueldhdez

# Tools information. Shown on Home and About pages.
tools:
  - name: Jekyll
    img: tool01.png
    url: http://jekyllrb.com/
  - name: BlackTie
    img: tool02.png
    url: http://blacktie.co/
  - name: Github Pages
    img: tool03.png
    url: https://pages.github.com/

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Dejando rastro de mi viaje hacia el conocimiento, compartiendo algunas historias y los proyectos más interesantes con los que me he tenido que topar y superar."

# Testimonial content. Shown on Home and About page.
testimonial:
    message: '"Solo por diversión"'
    author: Linus Torvalds
    position: CREADOR DE LINUX

# Contact message
contact: "No dudes enviar un mensaje, recibirás respuesta de inmediato."
