baseURL = 'https://mhdez.com/'
languageCode = 'en-us'
title = 'Miguel Hernández'
description = 'Curated notes on technology, software engineering, DevOps, and personal learnings. A collection of insights and discoveries from Miguel, a Software Engineer based in Leicester 🇬🇧, originally from Tenerife 🇮🇨.'
copyright = 'Miguel Hernández'
enableRobotsTXT = true

[module]
  [[module.imports]]
    path = 'github.com/michenriksen/hugo-theme-til'

[outputs]
  home = ['html']
  section = ['html', 'rss', 'json']
  page = ['html']

[menus]
  [[menus.main]]
    name = 'Notes'
    pageRef = '/notes'
    weight = 20
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 30
  [[menus.main]]
    name = 'Graph'
    pageRef = '/graph'
    weight = 40

[markup]
  [markup.highlight]
    noClasses = false
    style = 'tokyonight-night'

  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true

[params]
  # Set how dates should appear across the site.
  # For format options, visit https://gohugo.io/functions/time/format/
  dateFormat = ':date_long'

  # Show content graph for single notes and posts.
  showGraph = true

  # Author details for the JSON-LD structured data.
  [params.author]
    name = 'Miguel Hernández'
    email = 'me@mhdez.com'

  # Homepage setup
  [params.home]
    # Display recent blog posts on the homepage.
    showRecentPosts = false
    # Set how many recent blog posts to show.
    # recentPostsLimit = 3
    # Display recent notes on the homepage.
    showRecentNotes = false
    # Set how many recent notes to show.
    # recentNotesLimit = 10

  # Notes page setup
  [params.notes]
    # Set the number of notes to list on each page.
    pageSize = 20
    # Show a filter option for note categories above the notes list.
    showCategoryFilter = true

  [params.footer]
    creativeCommonsLicense = 'by_sa'
    showCreativeCommonsIcons = true
    showThemeCredit = true
