services:
  app:
    image: mcr.microsoft.com/devcontainers/go:2-1.26-trixie
    container_name: devcontainer_madh93_github_io
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
